### ISSUE TITLE
SVG Filter - Hardcoded path

### ISSUE THREAD

**Issue by arrubakook** [BurdaPraha/DrupalTwigFood#3]
Any chance this could be configurable?

Line 84 of src/TwigExtension/Food.php

`$fullPath   = "{$theme}/images/{$path}";`

**Comment by landsman** [comment]
Thank you for question. 
Sure, it could be. What you suggest?

**Comment by arrubakook** [comment]
I think replacing 

`$fullPath = "{$theme}/images/{$path}";`

with

`$fullPath = "{$theme}/{$path}";`

would allow a dev so specify any directory. What do you think?

P.S. Many thanks for your efforts on the module, i've found the naked_field filter particularly useful.

**Comment by landsman** [comment]
Ok, I'll change it.

**Comment by landsman** [comment]
Done, thanks.
https://github.com/BurdaPraha/DrupalTwigFood/commit/497133e736c62e6a4e159ffab830ce2a9b8557b1
